name: "💡 Filter Request"
description: Create a new ticket for a new feature request
title: "💡 [FILTER REQUEST] - <title>"
labels: [
  "question"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: dropdown
    id: adblocker-config
    attributes:
      label: "Ad Blocker Name"
      description: Please provide your Ad Blocker
      multiple: true
      options:
        - AdGuard
        - uBlock Origin
    validations:
      required: true
  - type: dropdown
    id: browser-type
    attributes:
      label: "Browser Name"
      description: Please provide your Browser
      multiple: true
      options:
        - Chrome (Chromium, Brave etc)
        - Mozilla Firefox
        - Other
    validations:
      required: true
  - type: textarea
    id: url
    attributes:
      label: "Site URL"
      description: Please enter the URL of the website you're having an issue with.
      placeholder: Please put ``` around the site name to avoid sending refers and attracting unneeded attention.
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: Please provide screenshots to help explain your problem.
      placeholder: No large screenshots please. Just the area in question and highlight the issue if possible.
      render: bash
    validations:
      required: true
  - type: textarea
    id: configs
    attributes:
      label: "Config"
      description: Please copy and paste any relevant Ad Blocker Config. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What is the impacted environment ?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false