name: Lock Threads

on:
  push:
    paths:
      - .github/workflows/lock-threads.yml
    branches-ignore:
      - dependabot/**
  schedule:
    # Once every month at At 00:05 UTC
    - cron: "5 0 * 8 *"
  issue_comment:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock-threads
  cancel-in-progress: ${{ github.event_name != 'issue_comment' }}

jobs:
  lock-threads:
    runs-on: ubuntu-latest
    steps:
      - name: Lock Outdated Threads
        uses: dessant/lock-threads@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          process-only: 'issues, prs'
          issue-inactive-days: 30
          add-issue-labels: outdated
          pr-inactive-days: 30
          add-pr-labels: outdated
